### ISSUE TITLE
Library not compiling for very common arduino boards

### ISSUE THREAD

**Issue by ernestum** [PaulStoffregen/TimerThree#2]
As you might have noticed I just forked you library to add methods to access the period and the current counter value. Before submitting the pull request I wanted to test if my slightly modified version at least compiles for various Arduino boards. Then I found out that it does not compile for the classics like Duemillanove, Uno, Nano and Mini. Others like the Mega, Leonardo and Yun work. Most of the Teensies work but the Teensy 3.0 does not!

Were you aware of this? I assume it would be a lot of work to port it to all these other boards but this limitation should at least be mentioned in the readme?

**Comment by PaulStoffregen** [comment]
I have only tested with the several boards I have on my desk.

If you can patch the code for others, and actually test on them to make sure it's really working, please send a pull request.  I would like to have all boards supported, but I don't have every type of board for testing (especially the very old Arduino models), nor do I have the time to test them all, even if the hardware were here.

**Comment by PaulStoffregen** [comment]
Duemillanove, Uno, Nano and Mini (all ATMEGA328) & Teensy 3.0 does not have Timer3.  This library can't magically make boards without that timer somehow work.  But you can use TimerOne.

**Comment by metawops** [comment]
Ohhhh ... Is the documentation over at https://docs.arduino.cc/libraries/timerthree/#Compatibility wrong, then?
Because there I read that an Arduino Nano is supported/compatible with TimerThree (and TimerFive, too).
