### ISSUE TITLE
Timer don't start and stop.

### ISSUE THREAD

**Issue by vabarca** [PaulStoffregen/TimerThree#5]
Compiling the timerthree1.1 stable library for the teensy 3.2, I was not able to start and stop the timer3 . I fixed it by changing the line 234 in TimerThree.h:

FTM2_SC = (FTM1_SC & (FTM_SC_TOIE | FTM_SC_PS(7))) | FTM_SC_CPWMS | FTM_SC_CLKS(1);
by
FTM2_SC = (FTM2_SC & (FTM_SC_TOIE | FTM_SC_PS(7))) | FTM_SC_CPWMS | FTM_SC_CLKS(1);

**Comment by PaulStoffregen** [comment]
Fixed.  Thanks!  https://github.com/PaulStoffregen/TimerThree/commit/2ec999f7bd3af11deb42c20f23292130b6033cfa
